#!/bin/bash

set -eu


# Move app root directory

cd $(dirname $0) && cd ..


# Prepare temporary deploy directory

unset tmpdir

function atexit() {
  [[ -n "${tmpdir}" ]] && rm -rf ${tmpdir}
}

trap atexit EXIT
trap 'rc=$?; trap - EXIT; atexit; exit $?' INT PIPE TERM

tmpdir=$(mktemp -d)


# Activate Service Account

gcloud auth activate-service-account --key-file ${GOOGLE_CREDENTIALS}


# Install dependencies

cd pkg
dep ensure
cd ..


# Deploy

cp app/*.yaml ${tmpdir}/
cp app/init.go ${tmpdir}/

packages=$(find pkg -mindepth 1 -maxdepth 1 -type d | grep -v vendor)

app_path=${PWD#${GOPATH}/}
mkdir -p ${tmpdir}/${app_path}/pkg

cp -r ${packages} ${tmpdir}/${app_path}/pkg/
cp -r pkg/vendor/* ${tmpdir}/src/

cd ${tmpdir}

export GOPATH=${tmpdir}

gcloud app deploy *.yaml --quiet --project ${GOOGLE_PROJECT}
